### ISSUE TITLE
python3 convesion

### ISSUE THREAD

**Issue by keithellis74** [ApproxEng/approxeng.input#2]
Hi Tom,

Firstly I'm not expecting you to run and fix this, but leaving this here incase you do get round to looking at it.

I've had a go at converting this to python3, initially I just replaced all ```print _statement_``` references with ```print(_statement_)``` but this did not work, so I ran the python 2to3 script on all the files in ```~/approxeng.input/src/python/approxeng/input``` and reinstalled with ```sudo python3 setup.py develop``` (I'm not running in a venv)

When running with ```python3 testinit.py ``` I get the following error:
```
pi@raspberrypi:~/repo/approxeng.input/scripts $ python3 testinit.py
Not importing evdev, expected during sphinx generation on OSX
Binding to Performance Designed Products Rock Candy Wireless Gamepad for PS3 at /dev/input/event0
Foo!
Traceback (most recent call last):
  File "testinit.py", line 12, in <module>
    with ControllerResource(controller=DualShock4(), device_name='Performance Designed Products Rock Candy Wireless Gamepad for PS3') as joystick:
  File "/home/pi/repo/approxeng.input/src/python/approxeng/input/asyncorebinder.py", line 33, in __enter__
    self.unbind = bind_controller(self.controller, device_name=self.device_name, device_path=self.device_path)
  File "/home/pi/repo/approxeng.input/src/python/approxeng/input/asyncorebinder.py", line 105, in bind_controller
    loop_thread = AsyncLoop(InputDeviceDispatcher())
  File "/home/pi/repo/approxeng.input/src/python/approxeng/input/asyncorebinder.py", line 96, in __init__
    self._set_daemon()
AttributeError: 'AsyncLoop' object has no attribute '_set_daemon'
pi@raspberrypi:~/repo/approxeng.input/scripts $
```  

This works as expected if I run ```python testinit.py```

**Comment by tomoinn** [comment]
Looks like evdev isn't loading - I have a conditional that allows me to build the docs on my mac even though it can't load evdev (because it's linux only) there, so it's possible your initial problem is that evdev isn't installed in your Python3, but in any case the AsyncCore stuff is definitely Python2.7, there are better ways to do the event loop poll under 3 which aren't available to 2.7, so all I need to do hopefully is drop in an alternative implementation using one of those more modern techniques and everything else should still work.

**Comment by tomoinn** [comment]
I replaced the asyncore code with one using selects in a secondary thread, testing on Python 3.5 and everything works just fine. Docs still need updating, but the code's good to go.

**Comment by keithellis74** [comment]
Great, thanks Tom, I have evdev installed for Python3 and am able to import and use it, so hopefully the new asyncore code will be good to go.  I'll try and test tonight.
Cheers.
Keith.

**Comment by keithellis74** [comment]
Hi Tom, had a play about with this tonight.  The python3 bit seems to be working now, but I can't work out how to connect the Rock Candy joypad.  It used to connect in the Python2 version.

I have a python3 script which connects to my Rock Candy:
```python
#!usr/bin/python3

# Testing evdev joystick input

import evdev
import sys
import time

class Joystick(object):

	def __init__(self, joystick = None):
		self.devices = [evdev.InputDevice(fn) for fn in evdev.list_devices()]
		if joystick is None:
			try:
				self.joystick = self.list_devices()[0]
			except:
				print('Could not locate joystick, check it is connected and try again')
				sys.exit()
		else:
			self.joystick = joystick
		self.device = evdev.InputDevice(self.joystick)

		# Lookup table for button/stick codes and types.
		# Dictionaty of buttons/sticks, looking up list of (Code / Type)
		# These are the codes for the Rock Candy PS3 controller
		self.controls=	{	'leftstick_x'		:	[0, 3],
							'leftstick_y'		[1, 3],
							'rightstick_x'		[2, 3],
							'rightstick_y'		[5, 3],
							'leftstick_push'	[314, 1],
							'rightstick_push'	[315, 1],
							'dpad_x'		[16, 3],
							'dpad_y'		[17, 3],
							'select'		[312, 1],
							'start'			[313, 1],
							'home'			[316, 1],
							'l1'			[308, 1],
							'l2'			[310, 1],
							'r1'			[309, 1],
							'r2'			[311, 1],
							'3dot'			[307, 1],
							'4dot'			[304, 1],
							'5dot'			[305, 1],
							'6dot'			[306, 1]}


	def list_devices(self):
		for device in self.devices:
			return (device.fn, device.name, device.phys)

	def list_capabilities(self):
		return self.device.capabilities()	

	def test_buttons(self):
		for event in self.device.read_loop() :
			if event.type == evdev.ecodes.EV_KEY:
				return evdev.categorize(event)
			elif event.type == evdev.ecodes.EV_ABS:
				result = evdev.categorize(event) , str(event.value)
				return result	
				
	def read_buttons(self):
		for event in self.device.read_loop():
			if event.type == evdev.ecodes.EV_KEY or event.type == evdev.ecodes.EV_ABS:
				return event
				
#	def read_buttons(self):
#		event = self.device.read()
#		if event.type == evdev.ecodes.EV_KEY or event.type == evdev.ecodes.EV_ABS:
#			return event
			
	def read_events(self):
		for event in self.device.read_loop():
			if event.type == evdev.ecodes.EV_KEY or event.type == evdev.ecodes.EV_ABS:
				print("Code = {0}, type = {1}, value = {2}".format(
						event.code, event.type, event.value))
				print('------------------------------------------------')
				
	def return_events(self):
		for event in self.device.read_loop():
			if event.type == evdev.ecodes.EV_KEY or event.type == evdev.ecodes.EV_ABS:
				return (event.code, event.type, event.value)
				
				
				
	def pressed(self, control):
		event = self.read_buttons()
		if event.code == self.controls[control][0]:
			return event.value
		else:
			return None
			
#	def code(self):
		



if __name__ == '__main__':
	joystick = Joystick()
	print(joystick.list_devices())
	print(joystick.list_capabilities())
	print('Testing, press buttons or move joysticks to test')
	running = True
	try: 
		while running:
			#print (joystick.test_buttons())
			events = joystick.return_events()	
			if events[0] == joystick.controls['leftstick_x'][0]:
				print('Left stick x moved',events[2])
			
			if events[0] == joystick.controls['leftstick_y'][0]:
				print('Left stick y moved',events[2])
			
			if events[0] == joystick.controls['rightstick_x'][0]:
				print('Right stick x moved',events[2])
			
			if events[0] == joystick.controls['rightstick_y'][0]:
				print('Right stick y moved',events[2])
				
			if events[0] == joystick.controls['3dot'][0]:
				print('3dot pressed',events[2])
			
			if events[0] == joystick.controls['4dot'][0]:
				print('4dot pressed',events[2])
			
			if events[0] == joystick.controls['5dot'][0]:
				print('5dot pressed',events[2])
			
			if events[0] == joystick.controls['6dot'][0]:
				print('6dot pressed',events[2])
				
			if events[0] == joystick.controls['l1'][0]:
				print('L1 pressed',events[2])
			
			if events[0] == joystick.controls['start'][0]:
				print('Start pressed',events[2])
			
			if events[0] == joystick.controls['select'][0]:
				print('select pressed',events[2])
			
			if events[0] == joystick.controls['r1'][0]:
				print('R1 pressed',events[2])
				print('Exiting...')
				time.sleep(2)
				running = False
				
			if events[0] == joystick.controls['start'][0] and events[0] == joystick.controls['select'][0]:
				print('R1 pressed',events[2])
				print('Exiting...')
				time.sleep(2)
				running = False
			
			
	
			
			
						
	except KeyboardInterrupt:
		print('	   Exiting ...')
		sys.exit()

	print("My work here is complete")
```

When I run this with ````python3 test.py````
I get the following output:
```
pi@raspberrypi:~/repo/joystick_test $ python3 test.py 
('/dev/input/event0', 'Performance Designed Products Rock Candy Wireless Gamepad for PS3', 'usb-3f980000.usb-1.4/input0')
{0: [0, 1, 3, 4], 1: [304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316], 3: [(0, AbsInfo(value=128, min=0, max=255, fuzz=0, flat=15, resolution=0)), (1, AbsInfo(value=128, min=0, max=255, fuzz=0, flat=15, resolution=0)), (2, AbsInfo(value=128, min=0, max=255, fuzz=0, flat=15, resolution=0)), (5, AbsInfo(value=128, min=0, max=255, fuzz=0, flat=15, resolution=0)), (16, AbsInfo(value=0, min=-1, max=1, fuzz=0, flat=0, resolution=0)), (17, AbsInfo(value=0, min=-1, max=1, fuzz=0, flat=0, resolution=0))], 4: [4]}
Testing, press buttons or move joysticks to test
3dot pressed 1
3dot pressed 0
4dot pressed 1
4dot pressed 0
5dot pressed 1
5dot pressed 0
Start pressed 1
Start pressed 0
select pressed 1
select pressed 0
Right stick y moved 211
Right stick y moved 255
Right stick y moved 172
Right stick y moved 128
Left stick x moved 17
Left stick x moved 0
Left stick y moved 8
Left stick y moved 20
Left stick y moved 21
Left stick y moved 23
Left stick y moved 24
Left stick x moved 128
``` 
etc.

Are you able to create a class from this for me?

**Comment by tomoinn** [comment]
Well, I've got one arriving tomorrow so it's probably not worth trying to sort this out online. What I'd need is the vendor and product ID from the evdev device, button codes, and the codes and possible numeric ranges of all analogue axes. If it's trying to be a PS3 stick they'll probably be the same and it'll be a question of copying that class.

**Comment by tomoinn** [comment]
It's not just a python 2 / 3 thing, a **lot** of stuff has changed!

**Comment by keithellis74** [comment]
Yeah, I worked out how to input the Rock Candy ID into your old code using the PS4 driver and it worked fine., but it's has changed a lot, with a bit more time I might be able to figure it out..  The info you need might be in the last code block I posted above.  But appreciate it would be easier with one in your hand.

```
('/dev/input/event0', 'Performance Designed Products Rock Candy Wireless Gamepad for PS3', 'usb-3f980000.usb-1.4/input0')
{0: [0, 1, 3, 4], 1: [304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316], 3: [(0, AbsInfo(value=128, min=0, max=255, fuzz=0, flat=15, resolution=0)), (1, AbsInfo(value=128, min=0, max=255, fuzz=0, flat=15, resolution=0)), (2, AbsInfo(value=128, min=0, max=255, fuzz=0, flat=15, resolution=0)), (5, AbsInfo(value=128, min=0, max=255, fuzz=0, flat=15, resolution=0)), (16, AbsInfo(value=0, min=-1, max=1, fuzz=0, flat=0, resolution=0)), (17, AbsInfo(value=0, min=-1, max=1, fuzz=0, flat=0, resolution=0))], 4: [4]}
```

I can't find a vendor ID though.

Cheers.

**Comment by tomoinn** [comment]
Should all be much simpler to use. The main difference is in how you acquire and bind controllers, and how you access their buttons and axes. The former is now trivial (once the controller class exists), in fact you can just do a 'give me the first thing that looks like a joystick' and it'll work, and because the latter now uses standardised names you can seamlessly switch between different controller types without having to make any code changes.

**Comment by tomoinn** [comment]
Vendor and product IDs are part of the InputDevice object, you should be able to pull them out with a bit of inspection.  Alternatively approxeng.input.controllers.print_devices() will just show everything, including those IDs

**Comment by tomoinn** [comment]
...then create a class, copying whatever's already closest, change the vendor and product IDs, add to approxeng.input.controllers.CONTROLLERS and it should all just work[tm]. Anyway, as I said, should have one tomorrow morning so will get it working then.

**Comment by keithellis74** [comment]
OK, I've created a class
```python
from approxeng.input import Controller, Button, CentredAxis, TriggerAxis, BinaryAxis

RC_VENDOR_ID = 3695
RC_PRODUCT_ID = 296


class RockCandy(Controller):
    """
    Driver for the Rock Candy PS3 controller
    """

    def __init__(self, dead_zone=0.05, hot_zone=0.05):
        """
        Create a new Rock Candy driver

        :param float dead_zone:
            Used to set the dead zone for each :class:`approxeng.input.CentredAxis` in the controller.
        :param float hot_zone:
            Used to set the hot zone for each :class:`approxeng.input.CentredAxis` in the controller.
        """
        super(RockCandy, self).__init__(vendor_id=RC_VENDOR_ID,
                                         product_id=RC_PRODUCT_ID,
                                         controls=[
                                             Button("Circle", 306, sname='circle'),
                                             Button("Cross", 305, sname='cross'),
                                             Button("Square", 304, sname='square'),
                                             Button("Triangle", 307, sname='triangle'),
                                             Button("Home (PS)", 316, sname='home'),
                                             Button("Share", 312, sname='select'),
                                             Button("Options", 313, sname='start'),
                                             Button("Trackpad", 317, sname='ps4_pad'),
                                             Button("L1", 308, sname='l1'),
                                             Button("R1", 309, sname='r1'),
                                             Button("L2", 310, sname='l2'),
                                             Button("R2", 311, sname='r2'),
                                             Button("Left Stick", 314, sname='ls'),
                                             Button("Right Stick", 315, sname='rs'),
                                             CentredAxis("Left Horizontal", 0, 255, 0, sname='lx'),
                                             CentredAxis("Left Vertical", 0, 255, 1, invert=True, sname='ly'),
                                             CentredAxis("Right Horizontal", 0, 255, 2, sname='rx'),
                                             CentredAxis("Right Vertical", 0, 255, 5, invert=True, sname='ry'),
                                             TriggerAxis("Left Trigger", 0, 255, 3, sname='lt'),
                                             TriggerAxis("Right Trigger", 0, 255, 4, sname='rt'),
                                             BinaryAxis("D-pad Horizontal", 16, b1name='dleft', b2name='dright'),
                                             BinaryAxis("D-pad Vertical", 17, b1name='dup', b2name='ddown')
                                         ],
                                         dead_zone=dead_zone,
                                         hot_zone=hot_zone)

    def __repr__(self):
        return 'Rock Candy PS3 controller'
```

Then in python3 shell
```python
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import approxeng.input.controllers
>>> from approxeng.input.controllers import find_controllers
>>> d = find_controllers()[0]
>>> d
{'controller': Rock Candy PS3 controller, 'physical_device': 'usb-3f980000.usb-1.4', 'devices': [InputDevice('/dev/input/event0')]}
>>> controller = d['controller']
>>> controller
Rock Candy PS3 controller
>>> devices = d['devices']
>>> devices
[InputDevice('/dev/input/event0')]
>>> print(controller)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/repo/approxeng.input/src/python/approxeng/input/__init__.py", line 174, in __str__
    return "{}, axes={}, buttons={}".format(self.__str__(), self.axes, self.buttons.buttons.keys())
  File "/home/pi/repo/approxeng.input/src/python/approxeng/input/__init__.py", line 174, in __str__
    return "{}, axes={}, buttons={}".format(self.__str__(), self.axes, self.buttons.buttons.keys())
...
...
 File "/home/pi/repo/approxeng.input/src/python/approxeng/input/__init__.py", line 174, in __str__
    return "{}, axes={}, buttons={}".format(self.__str__(), self.axes, self.buttons.buttons.keys())
RuntimeError: maximum recursion depth exceeded
```

This is basically ```select_binder_example.py``` in interactive mode.
If I comment out ```print(controller)``` it appears to work fine and the analogue sticks are detected.  

If I comment out the ```print(joystick)``` lines in ```testinit.py``` this detects the buttons correctly.

**Comment by tomoinn** [comment]
The infinite recursion bug ( #3 ) is dead, and was somewhat silly :man_facepalming: Thanks for reporting it!

**Comment by tomoinn** [comment]
This issue is no longer about P3 support (which I think is all working) so I'm closing for now. There's a (closed) issue for the rock candy support we can re-open if needed (see #4 )
